### ISSUE TITLE
исправить размер и позиционирование блока последние кейсы

### ISSUE THREAD

**Issue by daniilscherbina** [daniilscherbina/web-exam#74]
как сейчас 
![image](https://github.com/daniilscherbina/web-exam/assets/143995662/7134053f-f706-4aa7-af60-875bccf04593)

как должно быть
![image](https://github.com/daniilscherbina/web-exam/assets/143995662/362d4042-e0c6-447e-a9fc-192ce687dc29)

**Comment by ausf-software** [comment]
где изменения?
