### ISSUE TITLE
исправить футер 

### ISSUE THREAD

**Issue by daniilscherbina** [daniilscherbina/web-exam#82]
![image](https://github.com/daniilscherbina/web-exam/assets/143995662/399e2666-d861-42a5-a9e2-2b105546551c)
исправь сначала запулив изменения

**Comment by TechnoDamo** [comment]
я сейчас буду к диффурам готовиться, несколько часов осталось всего. Футер предлагаю откатить, там все нормально работало раньше.

**Comment by TechnoDamo** [comment]
ладно, футер еще сейчас  посмотрю

**Comment by TechnoDamo** [comment]
можно как-то получить версию до того рокового пулла?

**Comment by TechnoDamo** [comment]
а, только увидел сообщение про смещенный дедлайн

**Comment by daniilscherbina** [comment]
поздно, я уже переверстываю

**Comment by TechnoDamo** [comment]
короче до 23 точно на связи
